import './global.css';
import '../assets/css/bootstrap.min.css'

import Header from '@layouts/header';

export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <>
     <html>
      <Header/>
        <main>{children}</main>
      </html>
    </>
  );
} 
