import './global.css';
import '../assets/css/bootstrap.min.css'
import { Footer, Header } from '@main/app/_components/layouts';
import Provider from '@main/app/_providers'

export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
      <html>
        <body>
          <Header/>
            <main>
              <Provider>
                {children}     
              </Provider>
            </main>
          <Footer/>
        </body>
      </html>
  );
} 
